export const speech = [
  "baby a cecky",
  "bankokot",
  "byl jsem pochcán",
  "běž si ho vyhonit",
  "co se to tu děje",
  "co tak čumíš",
  "dort mám i na koulích",
  "dík žes mě pozval",
  "děláš chlapům jenom ostudu",
  "gratuluj semenu",
  "haha",
  "hahaha",
  "hou hou hou příchází stifler klaus",
  "huhaha",
  "huhahaha",
  "huhohoha",
  "jak se vede kočko",
  "jděte si ho vykouřit",
  "jedem do chicaga omrknout kozy",
  "jsem stylovej",
  "já se poseru",
  "já se snad pobleju",
  "já tam budu řádit",
  "kamaráde můžeš mi vylízat prdel",
  "každej by to chtěl se stifmeistrem",
  "kdo je tu čuramet",
  "konec hry",
  "kurevská paráda",
  "kurva dobrej dort",
  "kurva notak",
  "lisianhnus",
  "mám polevu i mezi půlkama",
  "mám rád starý lidi",
  "nejsou kundy, není tanec",
  "nevzdávejte se a jděte si za svým",
  "návod k čurákovi",
  "o čem se to bavíme",
  "po tréninku mě můžeš přeblafnout",
  "poslouchej ty řiťopichu",
  "používej kurva mozek",
  "píčusi",
  "rezervace",
  "samantiny cukrovinky",
  "seru na to",
  "tak jak zasraný parťáci",
  "tak to jsou teplí",
  "ten chlap mě fakt chtěl vojet",
  "ten čokl je skvělej",
  "teď do toho jdeme na vostro šmejde",
  "to byl ale kretén",
  "to je fantazie",
  "to je kurva nechutný",
  "to vás vy kokoti na vejšce nenanučili",
  "ty by sis ani neoholil koule",
  "ty ses snad úplně posral",
  "ty seš ale medvěd",
  "ty vyjebanče",
  "uhuhohahahahaa",
  "uhulahh",
  "uslyším haleluja",
  "uspořádáme rozlučku se svobodou",
  "už se toho průseru nemůžu dočkat",
  "voni jsou teplí",
  "vyhul mi hůl",
  "vyjebanej mozku",
  "vyser se na blbou švadlenku",
  "všechno nejpojebanější",
  "z kundy xichte",
  "zprostředkovatel mrdu",
  "čau z kundy xichte",
  "šáhni ji na prdel",
]
